# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVT3ouMrkp4lrqjvHOIdtE1vmWts0ACj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

datos = {
    "Mes": [
        "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
        "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
    ],
    "Portatiles": [20, 18, 25, 30, 28, 35, 40, 38, 36, 34, 32, 30],
    "Monitores": [15, 16, 14, 18, 20, 22, 24, 23, 21, 19, 18, 17],
    "Teclados": [40, 42, 38, 45, 47, 50, 55, 53, 52, 48, 46, 44]
}
df = pd.DataFrame(datos)

# Calculate Total_Mensual
df['Total_Mensual'] = df['Portatiles'] + df['Monitores'] + df['Teclados']

print("Primeras filas:")
print(df.head())
print("\nInformación del DataFrame:")
print(df.info())
print("\nEstadísticas descriptivas:")
print(df.describe())

ventas_portatiles = df["Portatiles"].values # convierte la Serie a array de numpy
media_port = np.mean(ventas_portatiles)
mediana_port = np.median(ventas_portatiles)
desv_port = np.std(ventas_portatiles)
print("Estadísticas Portátiles")
print("Media:", media_port)
print("Mediana:", mediana_port)
print("Desviación estándar:", desv_port)

ventas_Monitores = df["Monitores"].values # convierte la Serie a array de numpy
media_port = np.mean(ventas_Monitores)
mediana_port = np.median(ventas_Monitores)
desv_port = np.std(ventas_Monitores)
print("Estadísticas Monitores")
print("Media:", media_port)
print("Mediana:", mediana_port)
print("Desviación estándar:", desv_port)

ventas_Teclados = df["Teclados"].values # convierte la Serie a array de numpy
media_port = np.mean(ventas_Teclados)
mediana_port = np.median(ventas_Teclados)
desv_port = np.std(ventas_Teclados)
print("Estadísticas Teclados")
print("Media:", media_port)
print("Mediana:", mediana_port)
print("Desviación estándar:", desv_port)

plt.figure(figsize=(10, 5))
plt.plot(df["Mes"], df["Portatiles"], marker="o", label="Portátiles")
plt.plot(df["Mes"], df["Monitores"], marker="o", label="Monitores")
plt.plot(df["Mes"], df["Teclados"], marker="o", label="Teclados")
plt.title("Ventas mensuales por producto - TecnoPlus")
plt.xlabel("Mes")
plt.ylabel("Unidades vendidas")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
plt.bar(df["Mes"], df["Total_Mensual"])
plt.title("Ventas totales mensuales - TecnoPlus")
plt.xlabel("Mes")
plt.ylabel("Unidades totales vendidas")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

max_ventas_mes = df.loc[df['Total_Mensual'].idxmax()]
print("El mes con las ventas totales mas altas es:")
print(max_ventas_mes[['Mes','Total_Mensual']])